apiVersion: apps/v1
kind: Deployment
metadata:
  name: listen
  namespace: listen
  labels:
    app: listen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listen
  template:
    metadata:
      labels:
        app: listen
    spec:
      serviceAccount: listen
      containers:
        - name: listen
          image: quay.io/cporter/listen:1.05
          volumeMounts:
          - name: playbook-config-volume
            mountPath: /etc/playbook
      securityContext:
        readOnlyRootFilesystem: true
        allowPrivilegeEscalation: false
        capabilities:
            drop:
              - all
            add:
              - NET_BIND_SERVICE
        runaAsUser: 3001
        runaAsGroup: 3001
      volumes:
        - name: playbook-config-volume
          configMap:
            name: playbook
---
apiVersion: v1
kind: Service
metadata:
  name: listen
  namespace: listen
spec:
  type: ClusterIP
  selector:
    app: listen
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: listen
  namespace: listen
